theme: osuny-www-design-system
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
markup:
  goldmark:
    renderer:
      unsafe: true
